Upgrade to Ruby 2.2.5 and Rails 4.1.15
Note: Just upgrading Ruby without upgrading Rails was causing following
test to fail:
rspec spec/models/word_spec.rb:203
and it was caused by `user.flag_ids = some_array_of_flag_ids` to fail
with error:
*** NoMethodError Exception: undefined method `name' for nil:NilClass